### ISSUE TITLE
&filetype of Ruby is `ruby`

### ISSUE THREAD

**Issue by tsmsogn** [mopp/AOJ.vim#1]
Hi, thanks about your great plugin.

I think key of Ruby in [AOJ.vim](https://github.com/mopp/AOJ.vim/blob/master/plugin/aoj.vim#L7) would be `ruby` like bellow.

``` viml
let g:api4aoj#can_use_lang_dict = get(g:, 'api4aoj#can_use_lang_dict', { 'c' : 'C', 'cpp' : 'C++', 'java' : 'JAVA', 'cs' : 'C#','d' : 'D', 'ruby' : 'Ruby', 'python' : 'Python', 'php' : 'PHP', 'js' : 'JavaScript' })
```

**Comment by mopp** [comment]
Thank you for your cooperation :)
I fixed it based on your mention and this issue will be closed.

**Comment by tsmsogn** [comment]
@mopp Thanks :)
